services:
  server:
    build:
      context: .
      dockerfile: Dockerfile  
      target: final
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    develop:
      watch:
        - action: rebuild
          path: .
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    secrets:
      - db-password

  db:
    image: postgres
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  tests:
    build:
      context: .
      dockerfile: Dockerfile  
      target: test            
    command: ["dotnet", "test", "--no-build", "--logger:trx"]

volumes:
  db-data:

secrets:
  db-password:
    file: db/password.txt
